source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Font_Example' do
  pod 'Font', :path => '../'

  target 'Font_Tests' do
    inherit! :search_paths

    pod 'Quick',
        :git => 'https://github.com/norio-nomura/Quick.git',
        :branch => 'nn-swift-3-compatibility'
    pod 'Nimble',
        :git => 'https://github.com/norio-nomura/Nimble.git',
        :branch => 'nn-swift-3-compatibility'
  end
end

