source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.3'
use_frameworks!
inhibit_all_warnings!

target 'Font_Example' do
  pod 'Font', :path => '../'

  target 'Font_Tests' do
    inherit! :search_paths

    # NOTE: Edge builds needed to get past compilation crasher
    pod 'Quick', :git => 'https://github.com/Quick/Quick'
    pod 'Nimble', :git => 'https://github.com/Quick/Nimble'
  end
end

