# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode9
podfile: Example/Podfile
before_install:
- bundle install
- pod repo update > /dev/null 2>&1
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/Font.xcworkspace -scheme Font-Example -sdk iphonesimulator -destination platform="iOS Simulator,OS=latest,name=iPhone 6" ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
